const express = require('express');
const inventoryController = require('./inventory.controller');
const inventorySchemas = require('./inventory.schema');
const asyncHandler = require('../../utils/asyncHandler');
const validate = require('../../middleware/validate.middleware');
const { authenticate } = require('../../middleware/auth.middleware');
const { requirePermission } = require('../../middleware/permission.middleware');

const router = express.Router();

router.use(
  [
    '/item-categories',
    '/units',
    '/items',
    '/item-variants',
    '/warehouses',
    '/stock-balances',
    '/stock-movements',
    '/stock-adjustments'
  ],
  authenticate
);

router.get(
  '/item-categories',
  requirePermission('inventory.view'),
  validate(inventorySchemas.listCategorySchema),
  asyncHandler(inventoryController.listCategories)
);
router.post(
  '/item-categories',
  requirePermission('inventory.create'),
  validate(inventorySchemas.createCategorySchema),
  asyncHandler(inventoryController.createCategory)
);
router.get(
  '/item-categories/:id',
  requirePermission('inventory.view'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.getCategory)
);
router.patch(
  '/item-categories/:id',
  requirePermission('inventory.update'),
  validate(inventorySchemas.updateCategorySchema),
  asyncHandler(inventoryController.updateCategory)
);
router.delete(
  '/item-categories/:id/hard',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.hardDeleteCategory)
);
router.delete(
  '/item-categories/:id',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.deleteCategory)
);

router.get(
  '/units',
  requirePermission('inventory.view'),
  validate(inventorySchemas.listUnitSchema),
  asyncHandler(inventoryController.listUnits)
);
router.post(
  '/units',
  requirePermission('inventory.create'),
  validate(inventorySchemas.createUnitSchema),
  asyncHandler(inventoryController.createUnit)
);
router.get(
  '/units/:id',
  requirePermission('inventory.view'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.getUnit)
);
router.patch(
  '/units/:id',
  requirePermission('inventory.update'),
  validate(inventorySchemas.updateUnitSchema),
  asyncHandler(inventoryController.updateUnit)
);
router.delete(
  '/units/:id',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.deleteUnit)
);

router.get(
  '/items',
  requirePermission('inventory.view'),
  validate(inventorySchemas.listItemSchema),
  asyncHandler(inventoryController.listItems)
);
router.post(
  '/items',
  requirePermission('inventory.create'),
  validate(inventorySchemas.createItemSchema),
  asyncHandler(inventoryController.createItem)
);
router.get(
  '/items/:id',
  requirePermission('inventory.view'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.getItem)
);
router.patch(
  '/items/:id',
  requirePermission('inventory.update'),
  validate(inventorySchemas.updateItemSchema),
  asyncHandler(inventoryController.updateItem)
);
router.delete(
  '/items/:id/hard',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.hardDeleteItem)
);
router.delete(
  '/items/:id',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.deleteItem)
);

router.get(
  '/item-variants',
  requirePermission('inventory.view'),
  validate(inventorySchemas.listVariantSchema),
  asyncHandler(inventoryController.listVariants)
);
router.post(
  '/item-variants',
  requirePermission('inventory.create'),
  validate(inventorySchemas.createVariantSchema),
  asyncHandler(inventoryController.createVariant)
);
router.get(
  '/item-variants/:id',
  requirePermission('inventory.view'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.getVariant)
);
router.patch(
  '/item-variants/:id',
  requirePermission('inventory.update'),
  validate(inventorySchemas.updateVariantSchema),
  asyncHandler(inventoryController.updateVariant)
);
router.delete(
  '/item-variants/:id/hard',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.hardDeleteVariant)
);
router.delete(
  '/item-variants/:id',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.deleteVariant)
);

router.get(
  '/warehouses',
  requirePermission('inventory.view'),
  validate(inventorySchemas.listWarehouseSchema),
  asyncHandler(inventoryController.listWarehouses)
);
router.post(
  '/warehouses',
  requirePermission('inventory.create'),
  validate(inventorySchemas.createWarehouseSchema),
  asyncHandler(inventoryController.createWarehouse)
);
router.get(
  '/warehouses/:id',
  requirePermission('inventory.view'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.getWarehouse)
);
router.patch(
  '/warehouses/:id',
  requirePermission('inventory.update'),
  validate(inventorySchemas.updateWarehouseSchema),
  asyncHandler(inventoryController.updateWarehouse)
);
router.delete(
  '/warehouses/:id',
  requirePermission('inventory.delete'),
  validate(inventorySchemas.idSchema),
  asyncHandler(inventoryController.deleteWarehouse)
);

router.get(
  '/stock-balances',
  requirePermission('inventory.view'),
  validate(inventorySchemas.listStockBalanceSchema),
  asyncHandler(inventoryController.listStockBalances)
);
router.get(
  '/stock-movements',
  requirePermission('stock.movements'),
  validate(inventorySchemas.listStockMovementSchema),
  asyncHandler(inventoryController.listStockMovements)
);
router.post(
  '/stock-adjustments',
  requirePermission('stock.adjust'),
  validate(inventorySchemas.stockAdjustmentSchema),
  asyncHandler(inventoryController.adjustStock)
);

module.exports = router;
